database:
  driver: mysql
  username: root
  password: tabstorage
  #host: kernelgarden-db.cmcuy239248x.ap-northeast-2.rds.amazonaws.com
  #port: 3306
  name: diet
  logger:
  # kafka:
  #   brokers:
  #     - steamer-01.srvs.cloudkafka.com:9093
  #     - steamer-02.srvs.cloudkafka.com:9093
  #     - steamer-03.srvs.cloudkafka.com:9093
  #   topic: labs
behaviorLog:
  kafka:
  # brokers:
  #   - steamer-01.srvs.cloudkafka.com:9093
  #   - steamer-02.srvs.cloudkafka.com:9093
  #   - steamer-03.srvs.cloudkafka.com:9093
  # topic: labs
debug: true
service: diet
httpport: 8080